// ─────────────────────────────────────────────────────────────────────────────
//  src/models/Listing.model.js
//  Full listing schema — projects, notes, PYQs, syllabi
// ─────────────────────────────────────────────────────────────────────────────
import mongoose from 'mongoose';
import {
  LISTING_CATEGORIES,
  LISTING_STATUS,
  DELIVERY_FORMATS,
} from '../constants/index.js';

// ── Sub-schemas ───────────────────────────────────────────────────────────────

const imageSchema = new mongoose.Schema(
  {
    url:       { type: String, required: true },   // Cloudinary secure URL
    publicId:  { type: String, required: true },   // For Cloudinary deletion
    caption:   { type: String, default: '' },
  },
  { _id: false }
);

const videoSchema = new mongoose.Schema(
  {
    url:          { type: String, required: true },
    publicId:     { type: String, required: true },
    thumbnail:    { type: String, default: null }, // auto-generated by Cloudinary
    caption:      { type: String, default: '' },
    durationSecs: { type: Number, default: null },
  },
  { _id: false }
);

const previewFileSchema = new mongoose.Schema(
  {
    url:      { type: String, required: true },
    publicId: { type: String, required: true },
    fileType: { type: String, enum: ['pdf', 'image'], required: true },
  },
  { _id: false }
);

// ── Main Schema ───────────────────────────────────────────────────────────────

const listingSchema = new mongoose.Schema(
  {
    seller: {
      type:     mongoose.Schema.Types.ObjectId,
      ref:      'User',
      required: true,
      index:    true,
    },

    // ── Section 1: Basic Info ─────────────────────────────────────────────────
    title: {
      type:      String,
      required:  true,
      trim:      true,
      maxlength: 150,
    },

    tagline: {
      type:      String,
      trim:      true,
      maxlength: 200,
      default:   null,
    },

    category: {
      type:     String,
      enum:     Object.values(LISTING_CATEGORIES),
      required: true,
      index:    true,
    },

    domain: {
      type:  String,
      trim:  true,
      default: null,   // "Web Dev", "ML", "Physics"
    },

    subject: {
      type:  String,
      trim:  true,
      default: null,   // "Operating Systems", "Maths"
    },

    institution: {
      type:  String,
      trim:  true,
      default: null,   // "VIT Bhopal", "CBSE"
    },

    price: {
      type:     Number,
      required: true,
      min:      0,
    },

    isFree: {
      type:    Boolean,
      default: false,
    },

    // ── Section 2: Media ──────────────────────────────────────────────────────
    images: {
      type:     [imageSchema],
      default:  [],
      validate: {
        validator: (arr) => arr.length <= 10,
        message:   'Maximum 10 images allowed',
      },
    },

    videos: {
      type:     [videoSchema],
      default:  [],
      validate: {
        validator: (arr) => arr.length <= 2,
        message:   'Maximum 2 videos allowed',
      },
    },

    // ── Section 3: Description ────────────────────────────────────────────────
    description: {
      type:     String,
      required: true,
    },

    highlights: {
      type:    [String],
      default: [],
    },

    // ── Section 4: Tech & Links ───────────────────────────────────────────────
    techStack: {
      type:    [String],
      default: [],
    },

    liveLink: {
      type:    String,
      default: null,
    },

    githubLink: {
      type:    String,
      default: null,
    },

    // ── Section 5: Docs & Setup ───────────────────────────────────────────────
    readmeContent: {
      type:    String,
      default: null,
    },

    setupSteps: {
      type:    [String],
      default: [],
    },

    requirements: {
      type:    String,
      default: null,
    },

    previewFile: {
      type:    previewFileSchema,
      default: null,
    },

    // ── Section 6: Delivery ───────────────────────────────────────────────────
    // Actual delivery file lives in Transaction.deliveryFile (uploaded post-payment)
    deliveryFormat: {
      type:    String,
      enum:    Object.values(DELIVERY_FORMATS),
      default: null,
    },

    deliveryNote: {
      type:    String,
      default: null,
    },

    // ── Meta ──────────────────────────────────────────────────────────────────
    status: {
      type:    String,
      enum:    Object.values(LISTING_STATUS),
      default: LISTING_STATUS.DRAFT,
      index:   true,
    },

    // Computed score (0–100) driving a listing-completeness progress bar in UI
    completionScore: {
      type:    Number,
      min:     0,
      max:     100,
      default: 0,
    },

    views: {
      type:    Number,
      default: 0,
      min:     0,
    },

    likes: [{
      type: mongoose.Schema.Types.ObjectId,
      ref:  'User',
    }],

    likesCount: {
      type:    Number,
      default: 0,
      min:     0,
    },

    isFeatured: {
      type:    Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
// Full-text search across key fields
listingSchema.index(
  {
    title:       'text',
    description: 'text',
    techStack:   'text',
    subject:     'text',
    domain:      'text',
    institution: 'text',
    highlights:  'text',
  },
  { weights: { title: 10, techStack: 5, description: 2 } }
);

listingSchema.index({ seller: 1, status: 1 });
listingSchema.index({ category: 1, status: 1 });
listingSchema.index({ price: 1 });
listingSchema.index({ createdAt: -1 });

const Listing = mongoose.model('Listing', listingSchema);

export default Listing;
